import { RouteError } from '@/lib/route-error';

// Mock the domain module so we can control the generated byte size and skip
// running pdf-lib for the oversize / validation cases. Mirrors mcp-tools-nif.test.ts.
jest.mock('@/lib/angola/documents', () => ({
  generateInvoicePdf: jest.fn(),
  generateReceiptPdf: jest.fn(),
  generateContractPdf: jest.fn(),
}));

import { registerDocumentTools } from '@/lib/mcp/tools/documents';
import {
  generateInvoicePdf,
  generateReceiptPdf,
  generateContractPdf,
} from '@/lib/angola/documents';

const mockInvoice = generateInvoicePdf as jest.Mock;
const mockReceipt = generateReceiptPdf as jest.Mock;
const mockContract = generateContractPdf as jest.Mock;

type ResourceBlock = {
  type: string;
  text?: string;
  resource?: { uri: string; mimeType: string; blob: string };
};
type McpResult = { content: ResourceBlock[]; isError?: boolean };
type MockTools = Record<string, { meta: { title?: string; description?: string; inputSchema?: unknown }; handler: (input: unknown) => Promise<McpResult> }>;

function buildMockServer(): { mockServer: never; registeredTools: MockTools } {
  const registeredTools: MockTools = {};
  const mockServer = {
    registerTool: (
      name: string,
      meta: { title?: string; description?: string; inputSchema?: unknown },
      handler: (input: unknown) => Promise<McpResult>,
    ) => {
      registeredTools[name] = { meta, handler };
    },
  };
  return { mockServer: mockServer as never, registeredTools };
}

const TOOL_NAMES = ['generate_invoice_pdf', 'generate_receipt_pdf', 'generate_contract_pdf'] as const;

const MOCK_BY_TOOL: Record<(typeof TOOL_NAMES)[number], jest.Mock> = {
  generate_invoice_pdf: mockInvoice,
  generate_receipt_pdf: mockReceipt,
  generate_contract_pdf: mockContract,
};

describe('registerDocumentTools', () => {
  beforeEach(() => {
    mockInvoice.mockReset();
    mockReceipt.mockReset();
    mockContract.mockReset();
  });

  it('registers all 3 generate_*_pdf tools', () => {
    const { mockServer, registeredTools } = buildMockServer();
    registerDocumentTools(mockServer);

    for (const name of TOOL_NAMES) {
      expect(registeredTools[name]).toBeDefined();
    }
  });

  it('each tool has non-empty title and description naming a sibling generate_*_pdf tool', () => {
    const { mockServer, registeredTools } = buildMockServer();
    registerDocumentTools(mockServer);

    for (const name of TOOL_NAMES) {
      const tool = registeredTools[name].meta;
      expect(typeof tool.title).toBe('string');
      expect((tool.title ?? '').length).toBeGreaterThan(0);
      expect(typeof tool.description).toBe('string');
      expect((tool.description ?? '').length).toBeGreaterThan(0);
      expect(tool.description).toMatch(
        /generate_invoice_pdf|generate_receipt_pdf|generate_contract_pdf/,
      );
    }
  });

  it.each(TOOL_NAMES)(
    '%s success: returns 2-block resource+text result with no isError',
    async (name) => {
      const { mockServer, registeredTools } = buildMockServer();
      registerDocumentTools(mockServer);

      MOCK_BY_TOOL[name].mockResolvedValueOnce(new Uint8Array(64));

      const result = await registeredTools[name].handler({});

      expect(result.isError).toBeUndefined();
      expect(result.content).toHaveLength(2);

      const [resourceBlock, textBlock] = result.content;
      expect(resourceBlock.type).toBe('resource');
      expect(resourceBlock.resource?.mimeType).toBe('application/pdf');
      expect(resourceBlock.resource?.blob).toMatch(/^[A-Za-z0-9+/]+=*$/);
      expect((resourceBlock.resource?.blob ?? '').length).toBeGreaterThan(0);

      expect(textBlock.type).toBe('text');
      expect(textBlock.text).toContain('.pdf');
      expect(textBlock.text).toContain('64');
    },
  );

  it('generate_invoice_pdf size guard: oversized PDF → isError PDF_TOO_LARGE, retryable false', async () => {
    const { mockServer, registeredTools } = buildMockServer();
    registerDocumentTools(mockServer);

    // 3.1M bytes * 1.34 > 4_000_000
    mockInvoice.mockResolvedValueOnce(new Uint8Array(3_100_000));

    const result = await registeredTools['generate_invoice_pdf'].handler({});

    expect(result.isError).toBe(true);
    expect(result.content).toHaveLength(1);

    const parsed = JSON.parse(result.content[0].text ?? '{}');
    expect(parsed.code).toBe('PDF_TOO_LARGE');
    expect(parsed.retryable).toBe(false);
  });

  // T-04-03 mitigation: the Zod inputSchema must BOUND input size (not just shape),
  // so an unauthenticated caller cannot drive unbounded O(n) work before the output guard.
  it('generate_invoice_pdf inputSchema caps items array length (.max)', () => {
    const { mockServer, registeredTools } = buildMockServer();
    registerDocumentTools(mockServer);

    const schema = registeredTools['generate_invoice_pdf'].meta.inputSchema as {
      safeParse: (v: unknown) => { success: boolean };
    };
    const baseItem = { description: 'x', quantity: 1, unitPrice: 1, vatRate: 14 };
    const valid = {
      seller: { name: 'S' },
      buyer: { name: 'B' },
      items: Array.from({ length: 200 }, () => baseItem),
    };
    const oversized = {
      seller: { name: 'S' },
      buyer: { name: 'B' },
      items: Array.from({ length: 201 }, () => baseItem),
    };

    expect(schema.safeParse(valid).success).toBe(true);
    expect(schema.safeParse(oversized).success).toBe(false);
  });

  it('generate_contract_pdf inputSchema caps parties and clauses arrays (.max)', () => {
    const { mockServer, registeredTools } = buildMockServer();
    registerDocumentTools(mockServer);

    const schema = registeredTools['generate_contract_pdf'].meta.inputSchema as {
      safeParse: (v: unknown) => { success: boolean };
    };
    const party = { name: 'P' };

    const tooManyParties = {
      parties: Array.from({ length: 51 }, () => party),
      clauses: ['c'],
    };
    const tooManyClauses = {
      parties: [party, party],
      clauses: Array.from({ length: 201 }, () => 'c'),
    };

    expect(schema.safeParse({ parties: [party, party], clauses: ['c'] }).success).toBe(true);
    expect(schema.safeParse(tooManyParties).success).toBe(false);
    expect(schema.safeParse(tooManyClauses).success).toBe(false);
  });

  it('generate_invoice_pdf validation error: RouteError surfaces via shared mapping', async () => {
    const { mockServer, registeredTools } = buildMockServer();
    registerDocumentTools(mockServer);

    mockInvoice.mockRejectedValueOnce(
      new RouteError('INVALID_INVOICE_PAYLOAD', 'Invoice payload invalid.', 400),
    );

    const result = await registeredTools['generate_invoice_pdf'].handler({});

    expect(result.isError).toBe(true);
    expect(result.content).toHaveLength(1);

    const parsed = JSON.parse(result.content[0].text ?? '{}');
    expect(parsed.code).toBe('INVALID_INVOICE_PAYLOAD');
  });
});
